# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node@4.7
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    docker:
      - image: circleci/node@4.7
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node@4.7
    steps:
      - checkout
      - run: npm audit

workflows:  
  npmbuild:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test